# Configuration file for this project

weather_api:
  api_base_url: "https://api.open-meteo.com/v1/forecast"

  cities:
    - name: "london"
      lat: 51.5074
      lon: -0.1278
      timezone: "Europe/London"

    - name: "berlin"
      lat: 52.52
      lon: 13.41
      timezone: "Europe/Berlin"

    - name: "paris"
      lat: 48.8566
      lon: 2.3522
      timezone: "Europe/Paris"

    - name: "los_angeles"
      lat: 52.52
      lon: 13.41
      timezone: "America/Los Angeles"

    - name: "singapore"
      lat: 1.3521
      lon: 103.8198
      timezone: "Asia/Singapore"

  # Data requirements
  request_params:
    hourly_variables:
      - "temperature_2m"
      - "relative_humidity_2m"
      - "wind_speed_10m"
      - "visibility"
      - "precipitation"
      - "wind_direction_10m"

s3:
  bucket_name: "weather-pipeline-raw-maxwell-selassie"
  aws_region: "us-east-1"
  folders:
    - "raw"
    - "processed"
  partition_format: "year={year}/month={month}/day={day}"
